#!/usr/bin/env python3
"""Turn identified per-joint gains into a ready-to-paste Isaac Lab config snippet.

WHY THIS FILE EXISTS: the whole point of this project was to close the
sim2real gap for training -- that only matters if the identified gains
actually make it into `roto`'s training config. This reads every
results/params/<joint>_gains.yaml that validate.py has produced and emits:

  1. Updated `stiffness={...}` / `damping={...}` dicts in EXACTLY the format
     roto/roto/assets/shadow_hand_lite.py's `SHADOW_HAND_LITE_CFG` actuator
     block already uses (see that file's `ImplicitActuatorCfg`) -- so this is
     a drop-in replacement for the current placeholder values (Kp=1.0,
     Kd=0.1 uniformly), not a new format to integrate.

  2. A separate runtime-call snippet for Coulomb friction (Fc). Unlike
     stiffness/damping, `ImplicitActuatorCfg` in the version of Isaac Lab
     installed for this project does not expose a friction field directly at
     spawn time (not verified against every Isaac Lab version -- check your
     `ImplicitActuatorCfg` for a friction argument before assuming this).
     What IS confirmed working (see DECISIONS.md, tested directly against
     this installed version) is `Articulation.write_joint_friction_coefficient_to_sim(...)`,
     called once after the robot spawns -- e.g. in `RotoEnv.__init__` or
     `_setup_scene`, the same place shadow_hand_lite.py's other post-spawn
     setup would go.

Does not require Isaac Sim -- only reads YAML files.
"""

from __future__ import annotations

import argparse
import glob
import os

import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_HERE)


def load_all_gains(params_dir: str) -> dict:
    gains = {}
    for path in sorted(glob.glob(os.path.join(params_dir, "*_gains.yaml"))):
        with open(path, encoding="utf-8") as f:
            d = yaml.safe_load(f)
        gains[d["joint_name"]] = d
    return gains


def render_snippet(gains: dict, joint_cfg: dict) -> str:
    all_joints = joint_cfg["policy_joint_order"]
    missing = [j for j in all_joints if j not in gains]

    lines = []
    lines.append("# Auto-generated by shadow_pd_id/src/emit_config.py -- DO NOT hand-edit the")
    lines.append("# numbers below; re-run emit_config.py after re-running validate.py instead.")
    lines.append("#")
    if missing:
        lines.append(f"# WARNING: no identified gains found for: {missing}.")
        lines.append("# These joints are NOT included below -- keep their existing placeholder")
        lines.append("# values in shadow_hand_lite.py until they're identified too.")
        lines.append("#")
    lines.append("")
    lines.append("stiffness={")
    for j in all_joints:
        if j in gains:
            lines.append(f'    "{j}": {gains[j]["kp"]:.4f},')
    lines.append("},")
    lines.append("damping={")
    for j in all_joints:
        if j in gains:
            lines.append(f'    "{j}": {gains[j]["kd"]:.4f},')
    lines.append("},")
    lines.append("")
    lines.append("# --- Coulomb friction: apply via a runtime call after the robot spawns ---")
    lines.append("# (see this file's module docstring for why this isn't in the actuator cfg above)")
    lines.append("_IDENTIFIED_FRICTION = {")
    for j in all_joints:
        if j in gains:
            lines.append(f'    "{j}": {gains[j]["fc"]:.4f},')
    lines.append("}")
    lines.append("# for joint_name, fc in _IDENTIFIED_FRICTION.items():")
    lines.append("#     ridx = self.robot.joint_names.index(joint_name)")
    lines.append("#     self.robot.write_joint_friction_coefficient_to_sim(")
    lines.append("#         joint_friction_coeff=0.0,")
    lines.append("#         joint_dynamic_friction_coeff=fc,")
    lines.append("#         joint_viscous_friction_coeff=0.0,")
    lines.append("#         joint_ids=[ridx],")
    lines.append("#     )")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--params_dir", type=str, default=os.path.join(_PROJECT_ROOT, "results", "params"))
    parser.add_argument("--out_file", type=str,
                         default=os.path.join(_PROJECT_ROOT, "results", "identified_gains_isaaclab_snippet.py"))
    args = parser.parse_args()

    import sys

    sys.path.insert(0, _HERE)
    from load_data import load_joint_config

    joint_cfg = load_joint_config()
    gains = load_all_gains(args.params_dir)

    if not gains:
        print(f"No *_gains.yaml found in {args.params_dir} -- run validate.py for at least one joint first.")
        return

    snippet = render_snippet(gains, joint_cfg)
    with open(args.out_file, "w", encoding="utf-8") as f:
        f.write(snippet)

    print(f"Identified {len(gains)}/{len(joint_cfg['policy_joint_order'])} joints: {sorted(gains.keys())}")
    print(f"Wrote {args.out_file}")
    print()
    print("To use: open roto/roto/assets/shadow_hand_lite.py, find the active")
    print("SHADOW_HAND_LITE_CFG's ImplicitActuatorCfg (the un-commented one near the end of")
    print("the file), and replace its `stiffness=` / `damping=` dicts with the ones in the")
    print("generated file. Apply the friction snippet in RotoEnv.__init__ (roto/roto/tasks/")
    print("roto_env.py) or ShadowLiteEnv's setup, per the commented-out example above.")


if __name__ == "__main__":
    main()
